# Generated by Django 5.0.1 on 2024-02-09 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nexarc', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='voicetotext',
            name='language',
            field=models.CharField(default='', max_length=2000),
        ),
    ]
